// The `/` showcase seed: one readable document exercising every built-in block
// kind next to every bundled plugin's syntax, so a developer opening the dev app
// sees the whole surface at once. Array-joined rather than a template literal
// because the code/mermaid fences and inline code carry backticks; the block-math
// backslashes are doubled for the JS string, not the Markdown. This is the basic
// shell — the polished pitch document is roadmap item 7's, not this file's.
export const SHOWCASE_DOCUMENT = [
	'# aragonite',
	'',
	'A CST-based block editor for GFM Markdown. Every built-in block and every bundled plugin appears once below — edit freely.',
	'',
	'[[toc]]',
	'',
	'## Text and inline formatting',
	'',
	'A paragraph with **bold**, *italic*, ~~strikethrough~~, and `inline code`. Inline [links](https://github.com/voithos-labs/aragonite) render in place.',
	'',
	'Setext heading level 1',
	'======================',
	'',
	'Setext heading level 2',
	'----------------------',
	'',
	'A reference link resolves against a definition below: see the [project repository][repo].',
	'',
	'[repo]: https://github.com/voithos-labs/aragonite',
	'',
	'## Emoji :sparkles:',
	'',
	'GitHub-style shortcodes render as glyphs in prose — a rocket :rocket:, a party :tada:, a spark :sparkles: — while the literal `:name:` bytes stay in the source. They ride the bare `:` trigger, so they render in headings and table cells too.',
	'',
	'---',
	'',
	'## Blockquotes',
	'',
	'> A blockquote paragraph.',
	'>',
	'> > Nested one level deeper.',
	'',
	'## Lists',
	'',
	'- Unordered item',
	'- Another item',
	'  - Nested item',
	'',
	'1. Ordered item',
	'2. Second item',
	'',
	'- [x] Completed task',
	'- [ ] Pending task',
	'',
	'## Code',
	'',
	'```js',
	'function greet(name) {',
	'\treturn `Hello, ${name}!`;',
	'}',
	'```',
	'',
	'Indented code blocks parse too:',
	'',
	'    const indented = true;',
	'',
	'## Tables',
	'',
	'| Left | Center | Right |',
	'| :--- | :----: | ----: |',
	'| a :+1: | b      | c     |',
	'',
	'## HTML block',
	'',
	'<div class="note">',
	'\tRaw HTML blocks round-trip verbatim.',
	'</div>',
	'',
	'## Admonitions',
	'',
	':::note',
	'The admonitions plugin claims the five GitHub-alert kinds. Ordinary **Markdown** keeps working inside the fences.',
	':::',
	'',
	':::tip Pro tip',
	'A titled tip — the title rides the opener line.',
	':::',
	'',
	"GitHub's native `> [!TYPE]` alerts render as styled callouts too, their bytes untouched:",
	'',
	'> [!IMPORTANT]',
	'> Native alerts share the admonition chrome without rewriting the source to `:::`.',
	'',
	'## Collapsible details',
	'',
	'<details open>',
	'<summary>Implementation notes</summary>',
	'',
	'A `<details>` block holds real Markdown:',
	'',
	'- one point',
	'- another point',
	'',
	'</details>',
	'',
	'## Math',
	'',
	'Inline math flows in a sentence: the identity $a^2 + b^2 = c^2$ renders in place. Block math stands alone:',
	'',
	'$$',
	'\\int_0^1 x^2 \\, dx = \\frac{1}{3}',
	'$$',
	'',
	"GitHub's ```math fence is a third form, sharing the same rendered display:",
	'',
	'```math',
	'\\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a}',
	'```',
	'',
	'## Diagrams',
	'',
	'A mermaid fence renders as a diagram:',
	'',
	'```mermaid',
	'graph TD',
	'\tA[Parse] --> B[Render]',
	'\tB --> C[Serialize]',
	'```',
	'',
	'## Footnotes',
	'',
	'A claim can carry a footnote reference[^note], numbered by first-reference order. Its definition renders as an editable block below.',
	'',
	'[^note]: The definition body is real Markdown; edit it like any other block, and the reference number re-derives live.',
	''
].join('\n');
