// The `/` showcase seed: the pitch, told by a document that demonstrates while it explains.
// Array-joined rather than a template literal because the code/mermaid fences and inline code
// carry backticks; the block-math backslashes are doubled for the JS string, not the Markdown.
export const SHOWCASE_DOCUMENT = [
	'# aragonite',
	'',
	'A block editor whose source of truth is your Markdown, byte for byte. Parse it, edit it, save it, and `serialize(parse(source)) === source` still holds. This page is the editor and this document is live, so click anywhere and type.',
	'',
	'[[toc]]',
	'',
	'That outline is a plugin, and it is also just a block. Click an entry to jump to a section; click the block itself to edit its `[[toc]]` source.',
	'',
	'## Prose you already know how to write',
	'',
	'Markdown syntax stays visible but dimmed, so **bold**, *italic*, ~~strikethrough~~ and `inline code` never hide where they begin. Links work inline, like [the repository](https://github.com/voithos-labs/aragonite), and by reference, like [the docs][repo-docs], resolved against a definition kept further down.',
	'',
	'Select a word and every other occurrence of it lights up. That is a decoration: painted over the document, never written into it.',
	'',
	'[repo-docs]: https://github.com/voithos-labs/aragonite/tree/main/docs',
	'',
	'Structure without the furniture',
	'-------------------------------',
	'',
	'Everything here is a real block, and almost none of it looks like one. No cards, no per-block outline, no gutter chrome until you hover. (That heading is the Setext form, spelled with an underline instead of a `##`. Same level, different bytes, both round-trip.)',
	'',
	'> Quotes nest,',
	'>',
	'> > including into other quotes.',
	'',
	'### Lists and tasks',
	'',
	'1. Ordered lists renumber themselves as you split them.',
	'2. Unordered ones have less to worry about.',
	'',
	'- [x] A task is a list item with a checkbox',
	'- [ ] Click the box, or type the `x` in yourself',
	'',
	'#### Nesting goes as deep as you care to indent',
	'',
	'- One level',
	'  - Two levels',
	'    - Three, and a list windows its own children once there are enough of them to matter',
	'',
	'## Tables edit per cell',
	'',
	'Each cell is its own editing surface. `Tab` hops, `Enter` drops to the row below, and the delimiter row takes its canonical spelling the first time you touch the table.',
	'',
	'| What the parser meets  | What happens to it         |    Round-trips     |',
	'| :--------------------- | :------------------------- | :----------------: |',
	'| syntax it knows        | it renders as a block      | :white_check_mark: |',
	'| syntax a plugin claims | the plugin gets it         | :white_check_mark: |',
	'| syntax nobody claims   | it stays paragraph text    | :white_check_mark: |',
	'',
	'## Code, fenced and indented',
	'',
	'A fence highlights by language:',
	'',
	'```js',
	'function greet(name) {',
	'\treturn `Hello, ${name}!`;',
	'}',
	'```',
	'',
	'And the four-space form still parses, for every old README that uses it:',
	'',
	'    const indented = true;',
	'',
	'## Math',
	'',
	'Inline math sits inside a sentence: $a^2 + b^2 = c^2$. Display math stands on its own:',
	'',
	'$$',
	'\\int_0^1 x^2 \\, dx = \\frac{1}{3}',
	'$$',
	'',
	"GitHub's `math` fence is the same display written differently:",
	'',
	'```math',
	'\\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a}',
	'```',
	'',
	'## Diagrams',
	'',
	'A `mermaid` fence renders as a diagram. Double-click it to get the source back.',
	'',
	'```mermaid',
	'flowchart LR',
	'\tMD["raw markdown"] -->|parse| CST["CST"]',
	'\tCST -->|render| DOM["editable blocks"]',
	'\tCST -->|serialize| MD',
	'```',
	'',
	'## Admonitions',
	'',
	':::note',
	'A `:::name` directive belongs to a plugin, not to the parser. The plugin claims the name; what you write inside stays ordinary **Markdown**.',
	':::',
	'',
	':::tip Give it a title',
	'The title rides along on the opener line.',
	':::',
	'',
	"GitHub's own alert syntax renders as a callout too, with its bytes left alone:",
	'',
	'> [!IMPORTANT]',
	'> Nothing rewrote this into a `:::` directive. In the file it is still a blockquote wearing an alert marker.',
	'',
	'## Collapsible sections',
	'',
	'<details open>',
	'<summary>What lives inside a details block?</summary>',
	'',
	'Real Markdown, in real blocks:',
	'',
	'- editable in place',
	'- windowed like anything else',
	'',
	'</details>',
	'',
	'## Whatever else you paste',
	'',
	'<div class="unclaimed">',
	'\tRaw HTML nobody claims comes back out exactly as it went in.',
	'</div>',
	'',
	'So does syntax from a plugin you uninstalled last week[^plugins].',
	'',
	'[^plugins]: Footnotes are a plugin as well. The reference above numbers itself by order of first appearance, and this definition is an ordinary editable block.',
	'',
	'## Emoji :sparkles:',
	'',
	'Shortcodes render as glyphs while the literal `:name:` bytes stay in the file, in prose :rocket:, in headings, and in table cells.',
	'',
	'---',
	'',
	'That is the tour. All of it is editable, `Ctrl+F` searches it, and `Ctrl+Shift+D` opens the live syntax tree underneath it.',
	''
].join('\n');
