// The document the /plugins route mounts, kept importable so the library's own suite can
// pin every construct here to the plugin that claims it (`consumer-route-grammar.test.ts`).
export const PLUGINS_SEED = [
	'# Consumer plugins',
	'',
	'[[toc]]',
	'',
	':::callout Title',
	'Callout body',
	':::',
	'',
	'<details open>',
	'<summary>Summary</summary>',
	'',
	'Details body',
	'',
	'</details>',
	'',
	'Math $x^2$ inline',
	'',
	'$$e^{i\\pi} + 1 = 0$$',
	'',
	':::tip Consumer tip',
	'Admonition body',
	':::',
	'',
	'```mermaid',
	'graph TD',
	'  A --> B',
	'```',
	'',
	':::mystery',
	'Unregistered directive body',
	':::',
	'',
	'Emoji :sparkles: inline',
	'',
	'Footnote reference[^1] in prose',
	'',
	'[^1]: Footnote definition body',
	''
].join('\n');
