import { describe, it, expect, beforeAll, beforeEach } from 'vitest';
import fc from 'fast-check';
import { parse } from '$lib/core/parser';
import { serialize } from '$lib/core/serializer';
import { getPluginMetadata, type CstNode } from '$lib/core/nodes';
import { __resetSchemaRegistriesForTests } from '$lib/schema/registry-reset';
import { registerMermaidKind, type MermaidMetadata } from '$lib/plugins/mermaid/mermaid-kind';
import { freshOrFixedSeed } from '../../invariants/arbitraries';

// Adversarial fence shapes for serialize(parse(src)) === src, run in BOTH install
// states so uninstall safety comes out by construction. Pure byte identity, so even a
// code line that closes the fence early is a legal draw; reachability is pinned below.

const arbLineEnding = fc.constantFrom('\n', '\r\n');

const CODE_LINE_POOL = [
	'graph TD',
	'\tA[Start] --> B[End]',
	'A --> C',
	'',
	'  two leading spaces',
	'日本語ノード --> 中文',
	'label with 🎉 emoji',
	'~~~',
	'  ```'
];

const arbMermaidFence = fc
	.record({
		indent: fc.constantFrom('', ' ', '  ', '   '),
		char: fc.constantFrom('`', '~'),
		len: fc.integer({ min: 3, max: 5 }),
		infoRest: fc.constantFrom('', '   ', ' theme=dark', ' 日本語 flow'),
		openerEnding: arbLineEnding,
		codeLines: fc.array(fc.tuple(fc.constantFrom(...CODE_LINE_POOL), arbLineEnding), {
			maxLength: 5
		}),
		closer: fc.option(
			fc.record({
				indent: fc.constantFrom('', ' ', '   '),
				extraLen: fc.integer({ min: 0, max: 2 }),
				trail: fc.constantFrom('', ' ', '  '),
				ending: fc.constantFrom('\n', '\r\n', '')
			}),
			{ nil: undefined }
		),
		chopFinalNewline: fc.boolean()
	})
	.map(({ indent, char, len, infoRest, openerEnding, codeLines, closer, chopFinalNewline }) => {
		const opener = indent + char.repeat(len) + 'mermaid' + infoRest + openerEnding;
		const code = codeLines.map(([text, ending]) => text + ending).join('');
		const closerLine = closer
			? closer.indent + char.repeat(len + closer.extraLen) + closer.trail + closer.ending
			: '';
		const block = opener + code + closerLine;
		// An unclosed fence at EOF may also lack the final line ending.
		return !closer && chopFinalNewline ? block.replace(/(\r?\n)$/, '') : block;
	});

const arbDoc = fc
	.tuple(
		fc.constantFrom('', 'Above\n', 'Above\n\n', '# Heading\n\n'),
		arbMermaidFence,
		fc.constantFrom('', '\nAfter\n', '\n- a\n- b\n')
	)
	.map(([prefix, fence, suffix]) => prefix + fence + suffix);

const PARAMS = { numRuns: 300, seed: freshOrFixedSeed(20260710) } as const;

// fc.sample here feeds the reachability self-tests, which must stay deterministic
// (a fresh seed could miss a rare fence shape and flake), so its seed is left
// fixed rather than threaded through the fresh lane.
let samples: string[] = [];
beforeAll(() => {
	samples = fc.sample(arbDoc, { numRuns: 800, seed: 20260710 });
});

describe('mermaid round-trip property — plugin installed', () => {
	beforeEach(() => {
		__resetSchemaRegistriesForTests();
		registerMermaidKind();
	});

	it('serialize(parse(s)) === s over generated fence shapes', () => {
		fc.assert(
			fc.property(arbDoc, (src) => serialize(parse(src)) === src),
			PARAMS
		);
	});

	// Reachability evidence for the adversarial fence classes, read off the parsed
	// nodes' captured metadata (which also proves the capture reaches each shape).
	// The SAME arbitrary the properties run on must produce them.
	function sampledMermaidMetadata(): MermaidMetadata[] {
		const out: MermaidMetadata[] = [];
		for (const src of samples) {
			for (const block of parse(src).children as CstNode[]) {
				if ((block.kind as string) !== 'mermaid') continue;
				const meta = getPluginMetadata<MermaidMetadata>(block);
				if (meta) out.push(meta);
			}
		}
		return out;
	}
	const reachable: Array<[label: string, probe: (meta: MermaidMetadata) => boolean]> = [
		['CRLF line endings', (m) => m.openerLineEnding === '\r\n' || m.code.includes('\r\n')],
		['~~~ fences', (m) => m.fenceChar === '~'],
		['a missing closer at EOF', (m) => m.closerRaw === ''],
		['an indented opener', (m) => m.openerIndent.length > 0],
		['unicode in the code body', (m) => m.code.includes('日本語ノード')]
	];
	for (const [label, probe] of reachable) {
		it(`CAN generate ${label}`, () => {
			expect(sampledMermaidMetadata().some(probe)).toBe(true);
		});
	}
});

describe('mermaid round-trip property — plugin uninstalled', () => {
	beforeEach(() => __resetSchemaRegistriesForTests());

	it('the same generated bytes round-trip through the built-in grammar', () => {
		fc.assert(
			fc.property(arbDoc, (src) => {
				const doc = parse(src);
				if (doc.children.some((c) => (c.kind as string) === 'mermaid')) return false;
				return serialize(doc) === src;
			}),
			PARAMS
		);
	});
});
